config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:      'admins/password',
  registrations: 'admins/registrations'
  }
  
  devise_for :students, controllers: {
  sessions:      'students/sessions',
  passwords:      'students/password',
  registrations: 'students/registrations'
  }
  
  #--------admin側----------
  
  namespace :admin do
    resources :students, only: [:index, :show, :edit, :update]
  end
  
  #-------------------------
  
  #--------student側--------
  
  root 'homes#top'
  
  resources :students, only: [:index, :show, :edit, :update]
  resources :groups, only: [:create, :index, :show]
  resources :posts, only: [:create, :show]
  
  #-------------------------
  
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_notification.rb
class AdminNotification < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/belonging.rb
class Belonging < ApplicationRecord
  
  belongs_to :student
  belongs_to :group

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/curriculum.rb
class Curriculum < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  
  has_many :posts
  has_many :belongings
  has_many :students, through: :belongings
  accepts_nested_attributes_for :belongings
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :student
  belongs_to :group
  
end

app/models/progress.rb
class Progress < ApplicationRecord
end

app/models/reply.rb
class Reply < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :image

  has_many :posts
  has_many :belongings
  has_many :groups, through: :belongings
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div>
    <p class="footer-text text-center">© 2021 - MikitakaFukane</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffffff">
    <div class="container">
      <h3><%= link_to "BuddyChecker", root_path, class: "text-body font-italicn text-decoration-none logo-text" %></h3>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <% if student_signed_in?  %>
          <div class="nav-item mt-2 ml-5">
                ようこそ、<strong><%= current_student.name %></strong>さん！
          </div>
        <% end  %>
        <ul class="navbar-nav ml-auto">
          <% if student_signed_in? %>
            <li class="nav-item"><%= link_to "マイページ", "#", class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "生徒一覧", students_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "グループ", groups_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_student_session_path, method: :delete, class: "nav-link"  %></li>
          <% elsif current_admin %>
            <li class="nav-item"><%= link_to "商品一覧", "#", class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "会員一覧", "#", class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "注文履歴一覧", "#", class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "ジャンル一覧", "#", class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link"  %></li>
          <% else %>
            <li class="nav-item"><%= link_to "About", "#", class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "商品一覧", "#", class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "新規登録", new_student_registration_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "ログイン", new_student_session_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "管理者ログイン", new_admin_session_path, class: "nav-link"  %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuddyChecker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="footer-fixed">
      <%= render "layouts/header" %>
      <%#<%= render "layouts/flash" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>